CREATE TABLE IF NOT EXISTS `pre_adminauth` ( `username` text NOT NULL,`password` text NOT NULL) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT IGNORE INTO `pre_adminauth` VALUES('demo', 'addd204d606c9aac9f3e80853cd1c335');
INSERT IGNORE INTO `pre_adminauth` VALUES('admin', 'addd204d606c9aac9f3e80853cd1c335');
CREATE TABLE IF NOT EXISTS `pre_cdkey` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `key` int(11) NOT NULL,  `pwd` int(11) NOT NULL,  `type` text NOT NULL,  `tid` int(11) NOT NULL,  `amount` int(11) NOT NULL,  `comment` longtext NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;
CREATE TABLE IF NOT EXISTS `pre_config` (  `name` text NOT NULL,  `value` longtext NOT NULL) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT IGNORE INTO `pre_config` VALUES('site_name', '云中游戏');
INSERT IGNORE INTO `pre_config` VALUES('copyright', '云中谁寄锦书来，雁字回时，月满西楼。');
INSERT IGNORE INTO `pre_config` VALUES('index', '云中游戏致力于打造RM平台的网上商城。<br />');
CREATE TABLE IF NOT EXISTS `pre_items` (  `id` int(11) NOT NULL,  `name` text NOT NULL) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `pre_pages` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `title` text NOT NULL,  `content` longtext NOT NULL,  `order` tinyint(4) NOT NULL,  PRIMARY KEY (`id`),  KEY `id` (`id`)) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;
INSERT IGNORE INTO `pre_pages` VALUES(1, '关于我们', '呵呵哈哈~<br />', 0);
INSERT IGNORE INTO `pre_pages` VALUES(2, '联系我们', 'aaaatin@qq.com是个好主意。', 1);